### ISSUE TITLE
About the problem in API

### ISSUE THREAD

**Issue by tusher06** [VERSE-Equity/Toolkit-DHS#3]
Dear Concern
When I tried to run the VERSE Tool it showed the following message-

_"Some of your available datasets are not found in the DHS API. This is likely due to the DHS API being out of date and as such some of the meta information about your available datasets may not be available."_

My R version is v4.4.1 and RStudio version is v2024.04.2+764 and Windows 10

Would you please look at the issue.

Thank you

**Comment by bpatenaude** [comment]
Hello, which DHS survey (country and date) were you trying to access? Also to help us understand where the issue originates, can you please tell us the exact values that you typed in to the "required" fields for the VERSE tool before you tried to run it? There are numerous possible reasons for the error that you received and the above information will help us isolate the cause. IT could be because: 1. You used your DHS login credentials but did not request the DHS survey dataset on your DHS account (The VERSE Tool can only be run over datasets that you have permission to access)  2. The DHS survey child recode is not yet available (only applicable for new surveys) 3. The spelling of the country name is incorrect 4. The date is incorrect or 5. It is a brand new survey and our team needs to request access to it before it will run (if you are using the VERSE project credentials to log into the DHS instead of your own).

**Comment by tusher06** [comment]
Thank you for your response. I try to use Bangladesh 2017, 2014, 2011. However, it was happened with other countries also including Uganda 2017. Please help me. Moreover, I tried to  use the default one. Only change the working directory, country and year. More shoking that, the code was working last month but this week the problem started.

**Comment by bpatenaude** [comment]
Again, can you please tell me exactly what you put into the
"required" fields (copy and paste your code, please).

I checked the tool and confirm that with our DHS login credentials
Bangladesh 2011, 2014, 2017
Uganda 2016
All work completely fine with the VERSE Tool with no errors.

My best guess it that you failed to request access to these specific DHS
datasets on your DHS account, but I can't be sure until I see your exact
entries you made into the setup code.

Cheers,
Bryan

**Comment by tusher06** [comment]
Good Morning Dr Bryan
I attached my code here for your reference. Please have a look at it and guide me for it.
[VERSE-Kazi.zip](https://github.com/user-attachments/files/16258367/VERSE-Kazi.zip)

Thank you

**Comment by tusher06** [comment]
Dear Dr Bryan
I already resolved the problem. It happened to the permission of Windows 10. When I tried it another PC it worked fine. 

Thank you for this beautiful and useful tools. And again thank you for your prompt response to any issue.
